### ISSUE TITLE
Add per-language .gitignore

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-plugins#10]
## Please describe what you would like to see in this project

Instead of including a .gitignore in every plugin, we should define one per language.

## Please describe your use case

Avoid duplication.

## Additional context

The .gitignore file should be self-created and not copied off the Internet to avoid possible copyright issues.

**Comment by dustinblack** [comment]
@janosdebugs The [templates provided by GitHub](https://github.com/github/gitignore) are CC0 licensed, so can we not just use those freely?
