### ISSUE TITLE
Plugin to collect SUT metadata

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-plugins#14]
## Please describe what you would like to see in this project

This is inspired by and should be index-compatible with the cloud-bulldozer [metadata-collector](https://github.com/cloud-bulldozer/metadata-collector) and [stockpile](https://github.com/cloud-bulldozer/stockpile) tools. 

## Please describe your use case

SUT (system under test) metadata is collected with stockpile using ansible facts. Collected metadata is formatted to be indexed alongside benchmark data from other plugins.

## Additional context

This plugin work will need to coordinate with #12 and #13 to handle the ES indexing and compatibility.

**Comment by cpamnani** [comment]
I will be working on this issue as per the conversation with Dustin. Kindly assign this issue to me.

**Comment by dustinblack** [comment]
This week we discussed minimizing the MVP to simply to an ansible facts gathering and output it in whole as a dict.

**Comment by portante** [comment]
We have this with the pbench-agent tool meister sub-system collecting the system information.  Integration with that sub-system would bring that capability along with it.

**Comment by portante** [comment]
What is the determining factor that makes it longer or shorter?

**Comment by portante** [comment]
It is probably worth the effort to find out.

**Comment by dustinblack** [comment]
Closing with https://github.com/arcalot/arcaflow-plugin-metadata as an initial solution, though we will likely revisit this in the future for more explicit needs.
