### ISSUE TITLE
Handle smallfile version control from github release instead of tag

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-plugins#22]
## Please describe what you would like to see in this project

Smallfile currently uses a tag to clone a release, but tags can move. This could be problematic, so change the method to pull the release tarball instead.

**Comment by portante** [comment]
See also https://github.com/distributed-system-analysis/smallfile/issues/34

**Comment by portante** [comment]
Or consider using RPMs, PyPI, etc.

**Comment by dustinblack** [comment]
For now it looks like we have to stick with the release tag for smallfile until either a 1.1 release build is done or https://github.com/distributed-system-analysis/smallfile/issues/34 is addressed and smallfile 1.1 is available via PyPi. The latest release build is v1.0.1 which does not include the needed histogram features.

**Comment by dustinblack** [comment]
https://github.com/distributed-system-analysis/smallfile/issues/35

**Comment by portante** [comment]
I just released `smallfile` using the 1.1 tag, see https://github.com/distributed-system-analysis/smallfile/releases/tag/1.1.
